name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Chocolatey packages
        uses: actions/cache@v4
        with:
          path: C:\ProgramData\chocolatey
          key: choco-mingw-wix-${{ runner.os }}

      - name: Install MinGW-w64
        run: choco install mingw --yes

      - name: Install WiX Toolset
        run: choco install wixtoolset --yes --allow-downgrade

      - name: Build
        shell: cmd
        run: openwrt-connect-build.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-connect
          path: |
            openwrt-connect.exe
            openwrt-connect.msi
